name: "Build iStoreOS Installer ISO"

on:
  release:
    types: [published, edited]

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:

      - name: "Checking out git repository"
        uses: actions/checkout@v2
      
      - name: Set executable permissions
        run: |
          chmod +x ${{ github.workspace }}/istoreos.sh
          chmod +x ${{ github.workspace }}/supportFiles/istoreos/build.sh

      - name: "Build iStoreOS Installer ISO"
        run: |
          ./istoreos.sh ${{ github.event.release.tag_name }}
      
      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          body_path: ${{ github.workspace }}/supportFiles/istoreos/info.md
          files: |
            output/istoreos-*.iso
          token: ${{ secrets.GITHUB_TOKEN }}
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
