name: "Build iStoreOS 24.10.1 Installer ISO"

on:
 workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:

      - name: "Checking out git repository"
        uses: actions/checkout@v2
      
      - name: Set executable permissions
        run: |
          chmod +x ${{ github.workspace }}/istoreos.sh
          chmod +x ${{ github.workspace }}/supportFiles/istoreos/build.sh

      - name: "Build iStoreOS Installer ISO"
        run: |
          ./istoreos.sh
      
      - name: "Get Generated ISO File Name"
        run: |
          # 获取output目录下的ISO文件名
          ISO_FILE=$(ls -1 output/*.iso)
          echo "ISO_FILE=${ISO_FILE}" >> $GITHUB_ENV
          # 提取文件名用于tag
          ISO_NAME=$(basename "${ISO_FILE}" .iso)
          echo "ISO_NAME=${ISO_NAME}" >> $GITHUB_ENV
      
      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "${{ env.ISO_NAME }}"
          body_path: ${{ github.workspace }}/supportFiles/istoreos/info.md
          files: |
            ${{ env.ISO_FILE }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
